### ISSUE TITLE
Script para alterar o formulário dokan não funciona

### ISSUE THREAD

**Issue by wesguirra** [Luc45/PagarMeDokan#1]
Fala Lucas!

Muito obrigado por compartilhar o código!

Eu estou usando o WordPress 4.9.6
Com os plugins:

Dokan Lite 2.8.1
WooCommerce 3.4.1
WooCommerce Correios 3.7.1
WooCommerce Pagarme 2.0.11

tentei integrar com o WordPress aqui, por algum motivo o aviso `MUITA ATENÇÃO! O USUÁRIO CONFIGURADO PARA RECEBER AS COMISSÕES DO SPLIT PAYMENT ESTÁ COM DADOS DE PAGAMENTO INVÁLIDOS...` fica aparecendo, cadastrei a conta do usuário no dokan e na conta do Pagarme, mesmo assim o erro não some, eu estava procurando pela meta_key `conta_bancaria_pagarme`, mas ela não esta registrada no array de meta_keys do wordpress, estou supondo que seja algum problema na hora de cadastrar a conta já que comigo o override do formulário Dokan não aconteceu, e eu fiquei com uma enorme dúvida sobre onde devem estar os dados da conta do usuário.

Você chegou a ter esse problema? consegue me ajudar com isso?

Obrigado!

**Comment by wesguirra** [comment]
mais especificamente quando eu clico em Continuar no assistente do Dokan a página recarrega e não acontece nada.

**Comment by maportugal** [comment]
@wesleyguirra @Luc45 estou com o mesmo problema, alguma indicação de como resolver?

**Comment by wesguirra** [comment]
@maportugal desisti de usar esse repo o dono nao mantem mais e aparentemente tambem nao responde mais...

**Comment by luisaureliocasoni** [comment]
@wesleyguirra @maportugal Acabei precisando desse script agora. E descubri o problema. Se você está usando o Dokan em português, o script não vai conseguir ler a label da transferência bancária, que está escrito em inglês.

Assim, você precisa trocar o código da linha **156** do arquivo [pagarme_dokan.php](https://github.com/Luc45/PagarMeDokan/blob/master/pagarme_dokan.php) para:

`if ($('tbody').find('tr:first-child').find('label').text().toLowerCase() == 'transferência bancária')`

Ou troque 'transferência bancária' para qualquer outro nome que esteja usando.

Outra coisa importante, é necessário ativar no painel de administrador do Dokan a opção por "Transferência Bancária".
